### PR TITLE
liburing submodule & configure liburing in builder.py

### PR DESCRIPTION
**Pull request by luvjoey1996**
1. use submodule to manage liburing.
2.generate liburing/include/compat.h in build.py with configure script.

### CODE REVIEW

**Comment by YoSTEALTH** [comment]
@lovjoey1996

Thank you very much for your pr, i know you spent your precious time on this.

There are few things that doesn't quite work.
1. Me trying to build this raises a whole lot of cffi errors.
2. I was considering trying to run `./configure` myself but found out it doesn't play nice with cffi
3. Running `./configure` also installs C liburing into os lib somewhere? I don't want that either, as it could potentially conflict with os/user installs. Currently when you install using pip, liburing is installed in `site-packages/liburing/_liburing.so` this is very easy to manage and keep up to date.
4. `os.system()` is not recommended its better to use `subprocess.run()`

**Comment by luvjoey1996** [comment]
> @lovjoey1996
> 
> Thank you very much for your pr, i know you spent your precious time on this.
> 
> There are few things that doesn't quite work.
> 
> 1. Me trying to build this raises a whole lot of cffi errors.
> 2. I was considering trying to run `./configure` myself but found out it doesn't play nice with cffi
> 3. Running `./configure` also installs C liburing into os lib somewhere? I don't want that either, as it could potentially conflict with os/user installs. Currently when you install using pip, liburing is installed in `site-packages/liburing/_liburing.so` this is very easy to manage and keep up to date.
> 4. `os.system()` is not recommended its better to use `subprocess.run()`

could you mind to share some information with you linux distribution. It works fine in my local machine.
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	19.0
Codename:	Kyria
5.5.2-1-MANJARO

and run the **liburing.configure** script won't compile the source code or install some thing strange in your system but do some pre compile work which need to dedicate your system. **make install** does the stuff as you say, It will compile the source code and copy the include files into /usr/include and copy the dynamic lib generated into /usr/lib.

**Comment by YoSTEALTH** [comment]
I am on  5.5.2-1-MANJARO as well.

That's a good point `./configure` does not install.

Let me play around with it, see where it leads.

**Comment by luvjoey1996** [comment]
> @lovjoey1996
> 
> Thank you very much for your pr, i know you spent your precious time on this.
> 
> There are few things that doesn't quite work.
> 
> 1. Me trying to build this raises a whole lot of cffi errors.
> 2. I was considering trying to run `./configure` myself but found out it doesn't play nice with cffi
> 3. Running `./configure` also installs C liburing into os lib somewhere? I don't want that either, as it could potentially conflict with os/user installs. Currently when you install using pip, liburing is installed in `site-packages/liburing/_liburing.so` this is very easy to manage and keep up to date.
> 4. `os.system()` is not recommended its better to use `subprocess.run()`

this is the whole installation process on my machine
[https://asciinema.org/a/FhVWuAwI94Mn4TwNSJ69fKJYx](https://asciinema.org/a/FhVWuAwI94Mn4TwNSJ69fKJYx)

**Comment by YoSTEALTH** [comment]
This is how i made it look, works for me

https://bpaste.net/54MQ

**Comment by luvjoey1996** [comment]
> if you can replace `os.system('./configure')` with `subprocess.run('./configure')` i will accept it.

already fixed

**Comment by YoSTEALTH** [comment]
Thanks @luvjoey1996 this is actually a well needed change :)

**Pull request merged**
