### PR TITLE
add sockaddr_in support, fix helper socklen sockaddr bug

### PR DESCRIPTION
**Pull request by luvjoey1996**
1. helper function

- add support functions: liburing.build_sockaddr_in, liburing.sockaddr_in, you can use with io_uring_prep_connect, test with test/connect_test.py

2. bug fix

- liburing.sockaddr return value socklen initial with ffi.sizeof(addr) which is the size of addr pointer rather struct sockaddr.

### CODE REVIEW

**Comment by YoSTEALTH** [comment]
Hello @luvjoey1996

Thank again for your PR.

1. There are few flaws with this.
- `bzero()` function is deprecated http://man7.org/linux/man-pages/man3/bzero.3.html#CONFORMING_TO
- `inet_aton()` needs to check return for error.
- `htons()` function is deprecated https://docs.python.org/3/library/socket.html#socket.htons
- `printf()` can't just add it https://github.com/YoSTEALTH/Liburing/pull/2/files#diff-83aeab46a47575c8469d5d040f4eab0cR88 python has its own print function.
- `import pytest` wasn't used with `assert`
...

2. I can't tell if this is actually a bug, according to https://cffi.readthedocs.io/en/latest/ref.html#ffi-typeof-ffi-sizeof-ffi-alignof "For array = ffi.new("T[]", n), then ffi.sizeof(array) returns n * ffi.sizeof("T")."

Socket connections are very import...If I can I would like to avoid having to write my own `socket` module. You can refer to https://github.com/python/cpython/blob/master/Modules/socketmodule.c

**Comment by YoSTEALTH** [comment]
rather then using `inet_aton()`, `inet_pton()` can be used https://docs.python.org/3/library/socket.html#socket.inet_pton

**Comment by luvjoey1996** [comment]
I haven't realized that buildin socket module can do those things, let me do some fix.
and accroding to the cffi module, we may initialize with addr=ffi.new('struct sockaddr[] ', 1),got the size ffi.sizeof(addr).

Thank you for you suggestion.

**Comment by YoSTEALTH** [comment]
I wrote this, it looks like its working, but i don't think it actually connects! https://bpaste.net/ZN3A
I don't have time to debug if further today, figure i show you, just to give you some ideas.

**Comment by luvjoey1996** [comment]
> I wrote this, it looks like its working, but i don't think it actually connects! https://bpaste.net/ZN3A
> I don't have time to debug if further today, figure i show you, just to give you some ideas.

截图_2020-03-01_23-20-27
I try on my machine, and got this anwser.

**Comment by luvjoey1996** [comment]
> I wrote this, it looks like its working, but i don't think it actually connects! https://bpaste.net/ZN3A
> I don't have time to debug if further today, figure i show you, just to give you some ideas.

截图_2020-03-01_23-47-29

**Comment by YoSTEALTH** [comment]
Thanks for debugging @luvjoey1996 

This works for me: https://bpaste.net/PGQQ even tested it and it connects.

I am not sure why `inet_pton` was packing using `little` endian, all network related function should be `big` endian https://en.wikipedia.org/wiki/Endianness#Networking

**Comment by luvjoey1996** [comment]
> Hello @luvjoey1996
> 
> Thank again for your PR.
> 
> 1. There are few flaws with this.
> 
> * `bzero()` function is deprecated http://man7.org/linux/man-pages/man3/bzero.3.html#CONFORMING_TO it is recommended to use `memset()` but i don't think this is needed with cffi as its accounts for it?!
> * `inet_aton()` needs to check return for error.
> * `printf()` can't just add it https://github.com/YoSTEALTH/Liburing/pull/2/files#diff-83aeab46a47575c8469d5d040f4eab0cR88 python has its own print function.
> * `import pytest` wasn't used with `assert`
>   ...
> 
> 1. I can't tell if this is actually a bug, according to https://cffi.readthedocs.io/en/latest/ref.html#ffi-typeof-ffi-sizeof-ffi-alignof "For array = ffi.new("T[]", n), then ffi.sizeof(array) returns n * ffi.sizeof("T")."
> 
> Socket connections are very import...If I can I would like to avoid having to write my own `socket` module. You can refer to https://github.com/python/cpython/blob/master/Modules/socketmodule.c

I have solved the problem you point out, please review again

**Comment by luvjoey1996** [comment]
> Thanks for debugging @luvjoey1996
> 
> This works for me: https://bpaste.net/PGQQ even tested it and it connects.
> 
> I am not sure why `inet_pton` was packing using `little` endian, all network related function should be `big` endian https://en.wikipedia.org/wiki/Endianness#Networking

inet_pton does the right thing. In linux, which use little endian as the byteorder, when you try int.from_bytes method, this method will return a value, which has been stored in memory, but you think about linux how to store value, It change the bytes which return in inet_pton in a oppsite order. So, if you want to keep the byteorder won't change the internal order even in which case you have assignment statement (here a temp value has been stored in platform specific byteorder).
In here:
int.from_bytes(b'\x7f\x00\x00\x01', 'big') return 2130706433
2130706433 store in linux in b'\x01\x00\x00\x7f' ( int.to_bytes(2130706433, length=4, byteorder=sys.byteorder))
with an assignment sa.sin_addr.s_addr = 2130706433, to s_addr now is \x01\x00\x00\x7f
you want order don't change.
so int.from_bytes(b'\x7f\x00\x00\x01', sys.byteorder) return 16777343
16777343 store in linux in b'\x7f\x00\x00\x01' ( int.to_bytes(16777343, length=4, byteorder=sys.byteorder))

**Comment by YoSTEALTH** [comment]
I don't think you are running the test properly. PyTest only runs test function that start with name `test_` so the way to run `main()` is to name it `test_main():` then run it as `python3 -m pytest test` "test" being the test folder, it will run all the test files + functions.

**Comment by luvjoey1996** [comment]
> I don't think you are running the test properly. PyTest only runs test function that start with name `test_` so the way to run `main()` is to name it `def test_main(): ...` then run it as `python3 -m pytest test` "test" being the test folder, it will run all the test files + functions.
sorry, I have renamed the main function to test_main function.

**Comment by YoSTEALTH** [comment]
did you run the test to see if everything is a success?

**Pull request closed without merging**
