### PR TITLE
helper: add `decode_sockaddr` function

### PR DESCRIPTION
**Pull request by qweeze**

### CODE REVIEW

**Comment by YoSTEALTH** [comment]
`sockaddr_in` only supports `AF_INET` https://github.com/YoSTEALTH/Liburing/commit/0796467db7d43942f57096d6f5e0706f3a0825d5

**Comment by qweeze** [comment]
I tried to parse client's request in a webserver and realized that I have to extract its address from `sockaddr`. I wrote this function and thought maybe it would fit into helpers module since it already has `sockaddr_in` to convert `ip, port` to `sockaddr` and this is the inverse conversion
example:
```python
io_uring_prep_accept(sqe, fd, addr, addrlen, 0)
io_uring_submit(ring)
io_uring_wait_cqe(ring, cqes)
client_ip, client_port = decode_sockaddr(addr)
```

**Comment by YoSTEALTH** [comment]
Ok, I see.

> I wrote this function and thought maybe it would fit into helpers module

I really appreciate this :)

I do have few concerns:
- Something like this already exists in python `socket` module https://docs.python.org/3/library/socket.html#socket.socket.getpeername
- I take it you are not wrapping your `client` with python's `socket` module(thought its a pain)?
- There might be a security concern that socket must use os's `getpeername` (I can't remember what atm)
- Maybe using name `getpeername` might be better vs `decode_sockaddr`?
- Shouldn't https://github.com/qweeze/py_uring_sandbox/blob/master/benchmarks/uring_server.py#L90 be inside https://github.com/qweeze/py_uring_sandbox/blob/master/benchmarks/uring_server.py#L31 How does `decode_sockaddr(addr)` know which `client` the `addr` belongs to?
 
Sorry, I don't like to rush into things, if have to maintain this in the future I need to know what it does and provide some level of quality code for users.

**Comment by qweeze** [comment]
Thanks for the feedback!

I looked at `socket.getpeername` but it works only with python's `socket.socket` objects, I don't see how to get a `socket.socket` from a `sockaddr` struct. There's an internal function in `socketmodule.c` that could be used but it is not a part of public api - https://github.com/python/cpython/blob/master/Modules/socketmodule.c#L1294

> I take it you are not wrapping your client with python's socket module

Sorry, I'm not quite following here, what client did you mention?

> Shouldn't https://github.com/qweeze/py_uring_sandbox/blob/master/benchmarks/uring_server.py#L90 be inside https://github.com/qweeze/py_uring_sandbox/blob/master/benchmarks/uring_server.py#L31 

Yes, it should, I guess now it just reuses the same `addr` for each new client so that works, but of course it's incorrect and I should fix it.

Anyway, I see now that this implementation is very premature so I think I'll close this PR for now

**Comment by YoSTEALTH** [comment]
> Sorry, I'm not quite following here, what client did you mention?

This is a tiny sample code of how I wrote the `Socket` module https://github.com/YoSTEALTH/Shakti/blob/master/shakti/io/socket.py

I have already done a lot of what you are trying to do, Its just that I want the project to be a bit more stable before releasing to public.

**Pull request closed without merging**
